// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: multipaxos_kvstore/proto/paxos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BallotNumber represents (Term Number, Server ID)
type BallotNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TermNumber    int32                  `protobuf:"varint,1,opt,name=term_number,json=termNumber,proto3" json:"term_number,omitempty"`
	ServerId      int32                  `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotNumber) Reset() {
	*x = BallotNumber{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNumber) ProtoMessage() {}

func (x *BallotNumber) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNumber.ProtoReflect.Descriptor instead.
func (*BallotNumber) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *BallotNumber) GetTermNumber() int32 {
	if x != nil {
		return x.TermNumber
	}
	return 0
}

func (x *BallotNumber) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// LogEntry represents an atomic command for the state machine
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	BallotNum     *BallotNumber          `protobuf:"bytes,2,opt,name=ballot_num,json=ballotNum,proto3" json:"ballot_num,omitempty"`
	OpType        string                 `protobuf:"bytes,3,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"` // "Put", "Delete", "Get", "No-Op"
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetBallotNum() *BallotNumber {
	if x != nil {
		return x.BallotNum
	}
	return nil
}

func (x *LogEntry) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *LogEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Phase 1: Prepare RPC
type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"` // Nnew from the Candidate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareRequest) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

type PrepareResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Promise         bool                   `protobuf:"varint,1,opt,name=promise,proto3" json:"promise,omitempty"`                                       // true if Acceptor promises
	Ballot          *BallotNumber          `protobuf:"bytes,2,opt,name=ballot,proto3" json:"ballot,omitempty"`                                          // Echo back the ballot number
	AcceptedEntries []*LogEntry            `protobuf:"bytes,3,rep,name=accepted_entries,json=acceptedEntries,proto3" json:"accepted_entries,omitempty"` // Previously accepted log entries for safety reconciliation
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareResponse) GetPromise() bool {
	if x != nil {
		return x.Promise
	}
	return false
}

func (x *PrepareResponse) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *PrepareResponse) GetAcceptedEntries() []*LogEntry {
	if x != nil {
		return x.AcceptedEntries
	}
	return nil
}

// Phase 2: Accept RPC
type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Entry         *LogEntry              `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptRequest) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // true if Acceptor accepted
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`       // Index of the log entry
	Ballot        *BallotNumber          `protobuf:"bytes,3,opt,name=ballot,proto3" json:"ballot,omitempty"`      // Echo back the ballot number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AcceptResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AcceptResponse) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

// Client operations
type ClientPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPutRequest) Reset() {
	*x = ClientPutRequest{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPutRequest) ProtoMessage() {}

func (x *ClientPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPutRequest.ProtoReflect.Descriptor instead.
func (*ClientPutRequest) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *ClientPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ClientPutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ClientGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetRequest) Reset() {
	*x = ClientGetRequest{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetRequest) ProtoMessage() {}

func (x *ClientGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetRequest.ProtoReflect.Descriptor instead.
func (*ClientGetRequest) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *ClientGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ClientDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeleteRequest) Reset() {
	*x = ClientDeleteRequest{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeleteRequest) ProtoMessage() {}

func (x *ClientDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeleteRequest.ProtoReflect.Descriptor instead.
func (*ClientDeleteRequest) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *ClientDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`     // For Get operations
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Error message or status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{9}
}

func (x *ClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClientResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat for leader liveness
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderBallot  *BallotNumber          `protobuf:"bytes,1,opt,name=leader_ballot,json=leaderBallot,proto3" json:"leader_ballot,omitempty"`
	CommitIndex   int32                  `protobuf:"varint,2,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetLeaderBallot() *BallotNumber {
	if x != nil {
		return x.LeaderBallot
	}
	return nil
}

func (x *HeartbeatRequest) GetCommitIndex() int32 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

type HeartbeatResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LastLogEntryIndex int32                  `protobuf:"varint,2,opt,name=LastLogEntryIndex,proto3" json:"LastLogEntryIndex,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetLastLogEntryIndex() int32 {
	if x != nil {
		return x.LastLogEntryIndex
	}
	return 0
}

// message for state transfer
type StateTransfer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MissingEntries []*LogEntry            `protobuf:"bytes,1,rep,name=missing_entries,json=missingEntries,proto3" json:"missing_entries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateTransfer) Reset() {
	*x = StateTransfer{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransfer) ProtoMessage() {}

func (x *StateTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransfer.ProtoReflect.Descriptor instead.
func (*StateTransfer) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{12}
}

func (x *StateTransfer) GetMissingEntries() []*LogEntry {
	if x != nil {
		return x.MissingEntries
	}
	return nil
}

type StateTransferResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateTransferResult) Reset() {
	*x = StateTransferResult{}
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateTransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransferResult) ProtoMessage() {}

func (x *StateTransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_kvstore_proto_paxos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransferResult.ProtoReflect.Descriptor instead.
func (*StateTransferResult) Descriptor() ([]byte, []int) {
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP(), []int{13}
}

func (x *StateTransferResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_multipaxos_kvstore_proto_paxos_proto protoreflect.FileDescriptor

const file_multipaxos_kvstore_proto_paxos_proto_rawDesc = "" +
	"\n" +
	"$multipaxos_kvstore/proto/paxos.proto\x12\x05paxos\"L\n" +
	"\fBallotNumber\x12\x1f\n" +
	"\vterm_number\x18\x01 \x01(\x05R\n" +
	"termNumber\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x05R\bserverId\"\x95\x01\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x122\n" +
	"\n" +
	"ballot_num\x18\x02 \x01(\v2\x13.paxos.BallotNumberR\tballotNum\x12\x17\n" +
	"\aop_type\x18\x03 \x01(\tR\x06opType\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"=\n" +
	"\x0ePrepareRequest\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\"\x94\x01\n" +
	"\x0fPrepareResponse\x12\x18\n" +
	"\apromise\x18\x01 \x01(\bR\apromise\x12+\n" +
	"\x06ballot\x18\x02 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\x12:\n" +
	"\x10accepted_entries\x18\x03 \x03(\v2\x0f.paxos.LogEntryR\x0facceptedEntries\"c\n" +
	"\rAcceptRequest\x12+\n" +
	"\x06ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\x12%\n" +
	"\x05entry\x18\x02 \x01(\v2\x0f.paxos.LogEntryR\x05entry\"o\n" +
	"\x0eAcceptResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12+\n" +
	"\x06ballot\x18\x03 \x01(\v2\x13.paxos.BallotNumberR\x06ballot\":\n" +
	"\x10ClientPutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"$\n" +
	"\x10ClientGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\x13ClientDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"Z\n" +
	"\x0eClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"o\n" +
	"\x10HeartbeatRequest\x128\n" +
	"\rleader_ballot\x18\x01 \x01(\v2\x13.paxos.BallotNumberR\fleaderBallot\x12!\n" +
	"\fcommit_index\x18\x02 \x01(\x05R\vcommitIndex\"[\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x11LastLogEntryIndex\x18\x02 \x01(\x05R\x11LastLogEntryIndex\"I\n" +
	"\rStateTransfer\x128\n" +
	"\x0fmissing_entries\x18\x01 \x03(\v2\x0f.paxos.LogEntryR\x0emissingEntries\"/\n" +
	"\x13StateTransferResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x82\x02\n" +
	"\fPaxosService\x128\n" +
	"\aPrepare\x12\x15.paxos.PrepareRequest\x1a\x16.paxos.PrepareResponse\x125\n" +
	"\x06Accept\x12\x14.paxos.AcceptRequest\x1a\x15.paxos.AcceptResponse\x12>\n" +
	"\tHeartbeat\x12\x17.paxos.HeartbeatRequest\x1a\x18.paxos.HeartbeatResponse\x12A\n" +
	"\rTransferState\x12\x14.paxos.StateTransfer\x1a\x1a.paxos.StateTransferResult2\xba\x01\n" +
	"\rClientService\x125\n" +
	"\x03Put\x12\x17.paxos.ClientPutRequest\x1a\x15.paxos.ClientResponse\x125\n" +
	"\x03Get\x12\x17.paxos.ClientGetRequest\x1a\x15.paxos.ClientResponse\x12;\n" +
	"\x06Delete\x12\x1a.paxos.ClientDeleteRequest\x1a\x15.paxos.ClientResponseB\x1aZ\x18multipaxos_kvstore/protob\x06proto3"

var (
	file_multipaxos_kvstore_proto_paxos_proto_rawDescOnce sync.Once
	file_multipaxos_kvstore_proto_paxos_proto_rawDescData []byte
)

func file_multipaxos_kvstore_proto_paxos_proto_rawDescGZIP() []byte {
	file_multipaxos_kvstore_proto_paxos_proto_rawDescOnce.Do(func() {
		file_multipaxos_kvstore_proto_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multipaxos_kvstore_proto_paxos_proto_rawDesc), len(file_multipaxos_kvstore_proto_paxos_proto_rawDesc)))
	})
	return file_multipaxos_kvstore_proto_paxos_proto_rawDescData
}

var file_multipaxos_kvstore_proto_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_multipaxos_kvstore_proto_paxos_proto_goTypes = []any{
	(*BallotNumber)(nil),        // 0: paxos.BallotNumber
	(*LogEntry)(nil),            // 1: paxos.LogEntry
	(*PrepareRequest)(nil),      // 2: paxos.PrepareRequest
	(*PrepareResponse)(nil),     // 3: paxos.PrepareResponse
	(*AcceptRequest)(nil),       // 4: paxos.AcceptRequest
	(*AcceptResponse)(nil),      // 5: paxos.AcceptResponse
	(*ClientPutRequest)(nil),    // 6: paxos.ClientPutRequest
	(*ClientGetRequest)(nil),    // 7: paxos.ClientGetRequest
	(*ClientDeleteRequest)(nil), // 8: paxos.ClientDeleteRequest
	(*ClientResponse)(nil),      // 9: paxos.ClientResponse
	(*HeartbeatRequest)(nil),    // 10: paxos.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 11: paxos.HeartbeatResponse
	(*StateTransfer)(nil),       // 12: paxos.StateTransfer
	(*StateTransferResult)(nil), // 13: paxos.StateTransferResult
}
var file_multipaxos_kvstore_proto_paxos_proto_depIdxs = []int32{
	0,  // 0: paxos.LogEntry.ballot_num:type_name -> paxos.BallotNumber
	0,  // 1: paxos.PrepareRequest.ballot:type_name -> paxos.BallotNumber
	0,  // 2: paxos.PrepareResponse.ballot:type_name -> paxos.BallotNumber
	1,  // 3: paxos.PrepareResponse.accepted_entries:type_name -> paxos.LogEntry
	0,  // 4: paxos.AcceptRequest.ballot:type_name -> paxos.BallotNumber
	1,  // 5: paxos.AcceptRequest.entry:type_name -> paxos.LogEntry
	0,  // 6: paxos.AcceptResponse.ballot:type_name -> paxos.BallotNumber
	0,  // 7: paxos.HeartbeatRequest.leader_ballot:type_name -> paxos.BallotNumber
	1,  // 8: paxos.StateTransfer.missing_entries:type_name -> paxos.LogEntry
	2,  // 9: paxos.PaxosService.Prepare:input_type -> paxos.PrepareRequest
	4,  // 10: paxos.PaxosService.Accept:input_type -> paxos.AcceptRequest
	10, // 11: paxos.PaxosService.Heartbeat:input_type -> paxos.HeartbeatRequest
	12, // 12: paxos.PaxosService.TransferState:input_type -> paxos.StateTransfer
	6,  // 13: paxos.ClientService.Put:input_type -> paxos.ClientPutRequest
	7,  // 14: paxos.ClientService.Get:input_type -> paxos.ClientGetRequest
	8,  // 15: paxos.ClientService.Delete:input_type -> paxos.ClientDeleteRequest
	3,  // 16: paxos.PaxosService.Prepare:output_type -> paxos.PrepareResponse
	5,  // 17: paxos.PaxosService.Accept:output_type -> paxos.AcceptResponse
	11, // 18: paxos.PaxosService.Heartbeat:output_type -> paxos.HeartbeatResponse
	13, // 19: paxos.PaxosService.TransferState:output_type -> paxos.StateTransferResult
	9,  // 20: paxos.ClientService.Put:output_type -> paxos.ClientResponse
	9,  // 21: paxos.ClientService.Get:output_type -> paxos.ClientResponse
	9,  // 22: paxos.ClientService.Delete:output_type -> paxos.ClientResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_multipaxos_kvstore_proto_paxos_proto_init() }
func file_multipaxos_kvstore_proto_paxos_proto_init() {
	if File_multipaxos_kvstore_proto_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipaxos_kvstore_proto_paxos_proto_rawDesc), len(file_multipaxos_kvstore_proto_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_multipaxos_kvstore_proto_paxos_proto_goTypes,
		DependencyIndexes: file_multipaxos_kvstore_proto_paxos_proto_depIdxs,
		MessageInfos:      file_multipaxos_kvstore_proto_paxos_proto_msgTypes,
	}.Build()
	File_multipaxos_kvstore_proto_paxos_proto = out.File
	file_multipaxos_kvstore_proto_paxos_proto_goTypes = nil
	file_multipaxos_kvstore_proto_paxos_proto_depIdxs = nil
}
