// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/kvserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRequest is sent by clients to retrieve a value
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_kvserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvserver_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResponse returns the value for the key
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`      // True if key exists
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // Error message if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_kvserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PutRequest is sent by clients to store a key-value pair
type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_kvserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvserver_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// PutResponse confirms the put operation
type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_kvserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvserver_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ForwardUpdateRequest is sent by Primary to Backup for replication
type ForwardUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardUpdateRequest) Reset() {
	*x = ForwardUpdateRequest{}
	mi := &file_proto_kvserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardUpdateRequest) ProtoMessage() {}

func (x *ForwardUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardUpdateRequest.ProtoReflect.Descriptor instead.
func (*ForwardUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvserver_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardUpdateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ForwardUpdateRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ForwardUpdateResponse confirms the update
type ForwardUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardUpdateResponse) Reset() {
	*x = ForwardUpdateResponse{}
	mi := &file_proto_kvserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardUpdateResponse) ProtoMessage() {}

func (x *ForwardUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardUpdateResponse.ProtoReflect.Descriptor instead.
func (*ForwardUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvserver_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardUpdateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// SyncStateRequest is sent by Primary to transfer entire state to new Backup
type SyncStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // The entire key-value map
	ViewNumber    uint64                 `protobuf:"varint,2,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`                                            // The view number of this state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStateRequest) Reset() {
	*x = SyncStateRequest{}
	mi := &file_proto_kvserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateRequest) ProtoMessage() {}

func (x *SyncStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateRequest.ProtoReflect.Descriptor instead.
func (*SyncStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvserver_proto_rawDescGZIP(), []int{6}
}

func (x *SyncStateRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SyncStateRequest) GetViewNumber() uint64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

// SyncStateResponse confirms the state transfer
type SyncStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStateResponse) Reset() {
	*x = SyncStateResponse{}
	mi := &file_proto_kvserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateResponse) ProtoMessage() {}

func (x *SyncStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateResponse.ProtoReflect.Descriptor instead.
func (*SyncStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvserver_proto_rawDescGZIP(), []int{7}
}

func (x *SyncStateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_kvserver_proto protoreflect.FileDescriptor

const file_proto_kvserver_proto_rawDesc = "" +
	"\n" +
	"\x14proto/kvserver.proto\x12\x05proto\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"I\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"3\n" +
	"\vPutResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\x14ForwardUpdateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"'\n" +
	"\x15ForwardUpdateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xa3\x01\n" +
	"\x10SyncStateRequest\x125\n" +
	"\x04data\x18\x01 \x03(\v2!.proto.SyncStateRequest.DataEntryR\x04data\x12\x1f\n" +
	"\vview_number\x18\x02 \x01(\x04R\n" +
	"viewNumber\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11SyncStateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xf2\x01\n" +
	"\bKVServer\x12,\n" +
	"\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\x12,\n" +
	"\x03Put\x12\x11.proto.PutRequest\x1a\x12.proto.PutResponse\x12J\n" +
	"\rForwardUpdate\x12\x1b.proto.ForwardUpdateRequest\x1a\x1c.proto.ForwardUpdateResponse\x12>\n" +
	"\tSyncState\x12\x17.proto.SyncStateRequest\x1a\x18.proto.SyncStateResponseB&Z$github.com/praveenkullu/dsdemo/protob\x06proto3"

var (
	file_proto_kvserver_proto_rawDescOnce sync.Once
	file_proto_kvserver_proto_rawDescData []byte
)

func file_proto_kvserver_proto_rawDescGZIP() []byte {
	file_proto_kvserver_proto_rawDescOnce.Do(func() {
		file_proto_kvserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kvserver_proto_rawDesc), len(file_proto_kvserver_proto_rawDesc)))
	})
	return file_proto_kvserver_proto_rawDescData
}

var file_proto_kvserver_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_kvserver_proto_goTypes = []any{
	(*GetRequest)(nil),            // 0: proto.GetRequest
	(*GetResponse)(nil),           // 1: proto.GetResponse
	(*PutRequest)(nil),            // 2: proto.PutRequest
	(*PutResponse)(nil),           // 3: proto.PutResponse
	(*ForwardUpdateRequest)(nil),  // 4: proto.ForwardUpdateRequest
	(*ForwardUpdateResponse)(nil), // 5: proto.ForwardUpdateResponse
	(*SyncStateRequest)(nil),      // 6: proto.SyncStateRequest
	(*SyncStateResponse)(nil),     // 7: proto.SyncStateResponse
	nil,                           // 8: proto.SyncStateRequest.DataEntry
}
var file_proto_kvserver_proto_depIdxs = []int32{
	8, // 0: proto.SyncStateRequest.data:type_name -> proto.SyncStateRequest.DataEntry
	0, // 1: proto.KVServer.Get:input_type -> proto.GetRequest
	2, // 2: proto.KVServer.Put:input_type -> proto.PutRequest
	4, // 3: proto.KVServer.ForwardUpdate:input_type -> proto.ForwardUpdateRequest
	6, // 4: proto.KVServer.SyncState:input_type -> proto.SyncStateRequest
	1, // 5: proto.KVServer.Get:output_type -> proto.GetResponse
	3, // 6: proto.KVServer.Put:output_type -> proto.PutResponse
	5, // 7: proto.KVServer.ForwardUpdate:output_type -> proto.ForwardUpdateResponse
	7, // 8: proto.KVServer.SyncState:output_type -> proto.SyncStateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_kvserver_proto_init() }
func file_proto_kvserver_proto_init() {
	if File_proto_kvserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kvserver_proto_rawDesc), len(file_proto_kvserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kvserver_proto_goTypes,
		DependencyIndexes: file_proto_kvserver_proto_depIdxs,
		MessageInfos:      file_proto_kvserver_proto_msgTypes,
	}.Build()
	File_proto_kvserver_proto = out.File
	file_proto_kvserver_proto_goTypes = nil
	file_proto_kvserver_proto_depIdxs = nil
}
