// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/kvserver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KVServer_Get_FullMethodName           = "/proto.KVServer/Get"
	KVServer_Put_FullMethodName           = "/proto.KVServer/Put"
	KVServer_ForwardUpdate_FullMethodName = "/proto.KVServer/ForwardUpdate"
	KVServer_SyncState_FullMethodName     = "/proto.KVServer/SyncState"
)

// KVServerClient is the client API for KVServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KVServer service for key-value operations
type KVServerClient interface {
	// Get retrieves a value for a key (only handled by Primary)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Put stores a key-value pair (only handled by Primary)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// ForwardUpdate is called by Primary to replicate updates to Backup
	ForwardUpdate(ctx context.Context, in *ForwardUpdateRequest, opts ...grpc.CallOption) (*ForwardUpdateResponse, error)
	// SyncState is called by Primary to transfer entire state to new Backup
	SyncState(ctx context.Context, in *SyncStateRequest, opts ...grpc.CallOption) (*SyncStateResponse, error)
}

type kVServerClient struct {
	cc grpc.ClientConnInterface
}

func NewKVServerClient(cc grpc.ClientConnInterface) KVServerClient {
	return &kVServerClient{cc}
}

func (c *kVServerClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, KVServer_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServerClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, KVServer_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServerClient) ForwardUpdate(ctx context.Context, in *ForwardUpdateRequest, opts ...grpc.CallOption) (*ForwardUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardUpdateResponse)
	err := c.cc.Invoke(ctx, KVServer_ForwardUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServerClient) SyncState(ctx context.Context, in *SyncStateRequest, opts ...grpc.CallOption) (*SyncStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncStateResponse)
	err := c.cc.Invoke(ctx, KVServer_SyncState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVServerServer is the server API for KVServer service.
// All implementations must embed UnimplementedKVServerServer
// for forward compatibility.
//
// KVServer service for key-value operations
type KVServerServer interface {
	// Get retrieves a value for a key (only handled by Primary)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Put stores a key-value pair (only handled by Primary)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// ForwardUpdate is called by Primary to replicate updates to Backup
	ForwardUpdate(context.Context, *ForwardUpdateRequest) (*ForwardUpdateResponse, error)
	// SyncState is called by Primary to transfer entire state to new Backup
	SyncState(context.Context, *SyncStateRequest) (*SyncStateResponse, error)
	mustEmbedUnimplementedKVServerServer()
}

// UnimplementedKVServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKVServerServer struct{}

func (UnimplementedKVServerServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKVServerServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKVServerServer) ForwardUpdate(context.Context, *ForwardUpdateRequest) (*ForwardUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardUpdate not implemented")
}
func (UnimplementedKVServerServer) SyncState(context.Context, *SyncStateRequest) (*SyncStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncState not implemented")
}
func (UnimplementedKVServerServer) mustEmbedUnimplementedKVServerServer() {}
func (UnimplementedKVServerServer) testEmbeddedByValue()                  {}

// UnsafeKVServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVServerServer will
// result in compilation errors.
type UnsafeKVServerServer interface {
	mustEmbedUnimplementedKVServerServer()
}

func RegisterKVServerServer(s grpc.ServiceRegistrar, srv KVServerServer) {
	// If the following call pancis, it indicates UnimplementedKVServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KVServer_ServiceDesc, srv)
}

func _KVServer_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVServer_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServerServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVServer_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServerServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVServer_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServerServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVServer_ForwardUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServerServer).ForwardUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVServer_ForwardUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServerServer).ForwardUpdate(ctx, req.(*ForwardUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVServer_SyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServerServer).SyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVServer_SyncState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServerServer).SyncState(ctx, req.(*SyncStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KVServer_ServiceDesc is the grpc.ServiceDesc for KVServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KVServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.KVServer",
	HandlerType: (*KVServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KVServer_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _KVServer_Put_Handler,
		},
		{
			MethodName: "ForwardUpdate",
			Handler:    _KVServer_ForwardUpdate_Handler,
		},
		{
			MethodName: "SyncState",
			Handler:    _KVServer_SyncState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kvserver.proto",
}
