// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/viewservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// View represents the current system configuration
type View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber    uint64                 `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"` // Increments every time the view changes
	Primary       string                 `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`                          // Address of the primary server
	Backup        string                 `protobuf:"bytes,3,opt,name=backup,proto3" json:"backup,omitempty"`                            // Address of the backup server (can be empty)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_proto_viewservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_proto_viewservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_proto_viewservice_proto_rawDescGZIP(), []int{0}
}

func (x *View) GetViewNumber() uint64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *View) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *View) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

// PingRequest is sent by KV servers to announce they are alive
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`  // Name/address of the server sending ping
	ViewNumber    uint64                 `protobuf:"varint,2,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"` // The view number the server currently knows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_viewservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_viewservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_viewservice_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *PingRequest) GetViewNumber() uint64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

// PingResponse returns the current view
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_viewservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_viewservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_viewservice_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

// GetViewRequest is sent by clients to find the current primary
type GetViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewRequest) Reset() {
	*x = GetViewRequest{}
	mi := &file_proto_viewservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewRequest) ProtoMessage() {}

func (x *GetViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_viewservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewRequest.ProtoReflect.Descriptor instead.
func (*GetViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_viewservice_proto_rawDescGZIP(), []int{3}
}

// GetViewResponse returns the current view
type GetViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewResponse) Reset() {
	*x = GetViewResponse{}
	mi := &file_proto_viewservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewResponse) ProtoMessage() {}

func (x *GetViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_viewservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewResponse.ProtoReflect.Descriptor instead.
func (*GetViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_viewservice_proto_rawDescGZIP(), []int{4}
}

func (x *GetViewResponse) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

var File_proto_viewservice_proto protoreflect.FileDescriptor

const file_proto_viewservice_proto_rawDesc = "" +
	"\n" +
	"\x17proto/viewservice.proto\x12\x05proto\"Y\n" +
	"\x04View\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x04R\n" +
	"viewNumber\x12\x18\n" +
	"\aprimary\x18\x02 \x01(\tR\aprimary\x12\x16\n" +
	"\x06backup\x18\x03 \x01(\tR\x06backup\"O\n" +
	"\vPingRequest\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x1f\n" +
	"\vview_number\x18\x02 \x01(\x04R\n" +
	"viewNumber\"/\n" +
	"\fPingResponse\x12\x1f\n" +
	"\x04view\x18\x01 \x01(\v2\v.proto.ViewR\x04view\"\x10\n" +
	"\x0eGetViewRequest\"2\n" +
	"\x0fGetViewResponse\x12\x1f\n" +
	"\x04view\x18\x01 \x01(\v2\v.proto.ViewR\x04view2x\n" +
	"\vViewService\x12/\n" +
	"\x04Ping\x12\x12.proto.PingRequest\x1a\x13.proto.PingResponse\x128\n" +
	"\aGetView\x12\x15.proto.GetViewRequest\x1a\x16.proto.GetViewResponseB&Z$github.com/praveenkullu/dsdemo/protob\x06proto3"

var (
	file_proto_viewservice_proto_rawDescOnce sync.Once
	file_proto_viewservice_proto_rawDescData []byte
)

func file_proto_viewservice_proto_rawDescGZIP() []byte {
	file_proto_viewservice_proto_rawDescOnce.Do(func() {
		file_proto_viewservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_viewservice_proto_rawDesc), len(file_proto_viewservice_proto_rawDesc)))
	})
	return file_proto_viewservice_proto_rawDescData
}

var file_proto_viewservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_viewservice_proto_goTypes = []any{
	(*View)(nil),            // 0: proto.View
	(*PingRequest)(nil),     // 1: proto.PingRequest
	(*PingResponse)(nil),    // 2: proto.PingResponse
	(*GetViewRequest)(nil),  // 3: proto.GetViewRequest
	(*GetViewResponse)(nil), // 4: proto.GetViewResponse
}
var file_proto_viewservice_proto_depIdxs = []int32{
	0, // 0: proto.PingResponse.view:type_name -> proto.View
	0, // 1: proto.GetViewResponse.view:type_name -> proto.View
	1, // 2: proto.ViewService.Ping:input_type -> proto.PingRequest
	3, // 3: proto.ViewService.GetView:input_type -> proto.GetViewRequest
	2, // 4: proto.ViewService.Ping:output_type -> proto.PingResponse
	4, // 5: proto.ViewService.GetView:output_type -> proto.GetViewResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_viewservice_proto_init() }
func file_proto_viewservice_proto_init() {
	if File_proto_viewservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_viewservice_proto_rawDesc), len(file_proto_viewservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_viewservice_proto_goTypes,
		DependencyIndexes: file_proto_viewservice_proto_depIdxs,
		MessageInfos:      file_proto_viewservice_proto_msgTypes,
	}.Build()
	File_proto_viewservice_proto = out.File
	file_proto_viewservice_proto_goTypes = nil
	file_proto_viewservice_proto_depIdxs = nil
}
